#let content = (
  (
    company: [Abstract Machines],
    location: [Reno, NV (Remote)],
    role: [Founder & Principal],
    start: [Nov 2023],
    end: [Current],
    summary: [Founded Abstract Machines to lead technical strategy, technical feasibility assessment, applied R&D, and productization for client organizations, connecting engineering leadership with commercialization.],
    bullets: (
      [*Technical Discovery:* Led development and implementation of a technical discovery methodology that enabled a client to secure larger, more complex engagements, contributing #emph[\$550K in additional revenue.]],
      [*Technical Feasibility:* Evaluated technical viability and developed proofs of concept to reduce risk and inform commercialization decisions for emerging technologies, including subterranean leak detection systems and marketing attribution models, with #emph[IP/patent strategy support.]],
      [*Product Strategy:* Defined product roadmaps for clients bringing technical products to market, translating business objectives and technical feasibility into development priorities, sequencing, and go-to-market strategy.],
      [*Engineering & Product Leadership:* Led technical and product decision-making across client engagements, aligning engineering and product teams on delivery priorities and strengthening governance and planning through product manager training.],
    ),
  ),
  (
    company: [PROS],
    location: [Houston, TX (Remote)],
    role: [Product Manager],
    start: [May 2022],
    end: [Dec 2023],
    summary: [Owned product and platform strategy for PROS B2B Data Management, including roadmap, cross-product integration, and company-wide data infrastructure modernization.],
    bullets: (
      [*Platform Strategy & Resource Alignment:* Owned platform roadmap and drove cross-product integration strategy, partnering with platform architects and four engineering managers to prioritize work and align 30+ personnel across platform initiatives.],
      [*Platform Delivery:* Turned around a multi-year stalled data-platform initiative, leading the team to its first production deployment for the company-wide data platform.],
      [*Platform Economics:* Piloted a targeted platform cost reduction of 94%, saving approximately \$600K annually; tracked volume-based costs to improve product packaging and protect margins as platform usage scaled.],
      [*Data Quality:* Improved customer data-quality reporting, reducing the person-hours required for the same support workload by 40%.],
      [*Process Governance:* Partnered with the VP of Product to redesign product management processes, establishing company-wide standards for planning, estimation, and governance.],
    ),
  ),
  (
    company: [Loomis - US],
    location: [Houston, TX (Remote)],
    role: [Sr. Software Engineer],
    start: [Sep 2018],
    end: [May 2022],
    summary: [Owned and built the critical integration layer processing \$1B daily, orchestrating transaction flow across the SafePoint retail cash-deposit and provisional-credit platform.],
    bullets: (
      [*Platform Modernization:* Re-architected the critical integration layer, achieving zero-downtime migration, zero-second cutover, and self-healing recovery.],
      [*Systems Integration:* Designed and implemented bit-perfect, fully recoverable synchronization between incompatible databases, eliminating a critical blocker to platform modernization.],
      [*Operational Improvement:* Redesigned onboarding workflows with operational stakeholders, increasing Customer Support productivity by more than 60% without additional headcount.],
      [*Risk Management:* Partnered with stakeholders to assess risk and define rollout and recovery plans; contributed to the architecture and implementation of a new event-driven platform with transparent legacy system integration.],
    ),
  ),
  (
    company: [Progeny Systems],
    location: [Las Vegas, NV],
    role: [Technical Lead],
    start: [May 2010],
    end: [Sep 2018],
    summary: [Technical lead for DoD SBIR research programs, leading three development teams across applied research, prototype development, and productization, with research outcomes enabling Phase III commercialization and DoD adoption.],
    bullets: (
      [*SBIR Capture & Commercialization:* Individually generated \$1M in revenue during 2016–2018 across three Phase I and II SBIR awards. Productized a first-of-its-kind mobile application integrating with IBM Maximo to modernize Naval Fuel Depot asset management.],
      [*SBIR Proposal Development:* Primarily authored the winning Phase I proposal and provided technical product guidance for Naval health and wellness information ashore and afloat; additional awarded work addressed mobile forms, guides, and on-site training for Naval galley kitchens.],
      [*Applied Research & Commercialization:* Developed OCR capabilities and conducted research under Phase I and II SBIR programs to digitize and trace schematics for high-pressure system safety procedures and maintenance. Research outcomes directly enabled Phase III commercialization and DoD adoption.],
      [*R&D Engineering Leadership:* Led and mentored three engineering teams totaling 12 developers across concurrent DoD R&D programs, including training on secure systems integration and DoD software requirements.],
    ),
  ),
)
