#let content = (
  (
    company: [Abstract Machines],
    location: [Reno, NV (Remote)],
    role: [Founder & Principal],
    start: [Nov 2023],
    end: [Current],
    summary: [Founded firm to lead clients’ technical strategy, feasibility, applied R&D, productization, and commercialization.],
    bullets: (
      [*Technical Discovery:* Developed and operationalized a technical discovery methodology combining R&D, prototyping, and product planning, enabling larger, more complex client engagements and contributing #emph[\$550K in additional revenue.]],
      [*Marketing Attribution R&D:* Researched, prototyped, and refined a client’s marketing attribution model concept; supported patent filings.],
      [*Leak Detection Feasibility:* Helped guide designs for an early subterranean leak-detection proof of concept and estimate long-term development to market.],
      [*Product Strategy:* Owned client roadmap decisions on technical architecture, feasibility, sequencing, and investment tradeoffs, aligning strategy with commercialization goals.],
      [*Engineering & Product Leadership:* Led engineering and product decisions across engagements, aligning delivery priorities and strengthening planning and governance; trained product managers on execution and decision frameworks.],
    ),
  ),
  (
    company: [PROS],
    location: [Houston, TX (Remote)],
    role: [Product Manager],
    start: [May 2022],
    end: [Dec 2023],
    summary: [Owned PROS B2B Data Management strategy, roadmap, cross-product integration, and company-wide data infrastructure modernization.],
    bullets: (
      [*Platform Leadership:* Aligned platform priorities with architects and four engineering managers across 30+ personnel in engineering, sales, product, and customer~organizations.],
      [*Platform Delivery:* Turned around a multi-year stalled data platform, leading the team to its first production deployment.],
      [*Platform Economics:* Cut total platform costs by 94%, saving approximately \$600K annually; tracked usage-based costs to guide packaging and protect margins.],
      [*Data Quality:* Improved data-quality reporting, cutting support person-hours by 40% for the same workload.],
      [*Process Governance:* Partnered with the VP of Product to establish company-wide product planning, estimation, and governance standards.],
    ),
  ),
  (
    company: [Loomis - US],
    location: [Houston, TX (Remote)],
    role: [Sr. Software Engineer],
    start: [Sep 2018],
    end: [May 2022],
    summary: [Owned and built the integration layer moving millions of transactions totaling \$1B daily across SafePoint’s retail cash-deposit and provisional-credit platform.],
    bullets: (
      [*Platform Modernization:* Re-architected the critical integration layer, achieving zero-downtime migration, zero-second cutover, and self-healing recovery.],
      [*Systems Integration:* Engineered bit-perfect, fully recoverable synchronization between incompatible databases, removing a critical modernization blocker.],
      [*Operational Improvement:* Defined onboarding requirements, implemented automation and integrations, and raised Customer Support productivity over 60% without added headcount.],
      [*Risk Management:* Assessed risk and defined rollout and recovery plans with stakeholders; helped architect and implement an event-driven platform integrating legacy systems.],
    ),
  ),
  (
    company: [Progeny Systems],
    location: [Las Vegas, NV],
    role: [Technical Lead],
    start: [May 2010],
    end: [Sep 2018],
    summary: [Led three teams across DoD SBIR research, prototyping, and productization, with outcomes enabling Phase III commercialization and DoD adoption.],
    bullets: (
      [*SBIR Capture & Commercialization:* Individually generated \$1M in SBIR funding (2016–2018) across three Phase I/II awards. Productized a first-of-its-kind mobile application integrating Naval Fuel Depot asset management with IBM Maximo.],
      [*SBIR Proposal Development:* Primarily authored an awarded Phase I proposal and guided technical product development for Naval health information ashore and afloat; additional awarded work supported mobile tools and training for Naval galleys.],
      [*Applied Research & Commercialization:* Developed schematic-symbol recognition, tracing, and classification algorithms and an image-processing engine for interactive canvases. This Phase I/II SBIR R&D enabled Phase III commercialization and DoD adoption.],
      [*R&D Engineering Leadership:* Led and mentored developers across three concurrent DoD R&D teams, training them on secure integration and DoD software requirements.],
    ),
  ),
)
